### ISSUE TITLE
how to install naoqi_libqicore?

### ISSUE THREAD

**Issue by 3038922** [ros-naoqi/naoqi_driver#119]
my system is ubuntu1804 
ros --version is melodic .
if i input `rosdep install -i -y --from-paths ./naoqi_driver`
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
naoqi_driver: Cannot locate rosdep definition for [naoqi_libqicore]
```

**Comment by Pandhariix** [comment]
Hi,

The naoqi_libqicore package has not yet been released for melodic, you won't be able to get it through rosdep or apt-get.

**Comment by 3038922** [comment]
https://github.com/aldebaran/libqicore ->naoqi_libqicore
https://github.com/aldebaran/libqi -> naoqi_libqi
I am a novice, can you tell me how to compile libqicore? How to compile is not written in the document

**Comment by Pandhariix** [comment]
To compile those packages for naoqi_driver, you would need to modify them so that they match the format of ROS packages (named naoqi_libqi and naoqi_libqicore instead of libqi and libqicore), put them in the catkin workspace of your naoqi_driver repo and compile everything with catkin.

But this is not an easy task, extra modifications should be brought to libqi and libqicore in order to compile them for ubuntu 18 (mainly because of boost compatibility issues). I've opened an [issue](https://github.com/ros-naoqi/libqi-release/issues/6) regarding the release of naoqi_libqi and naoqi_libqicore for melodic. With those 2 packages released, compiling naoqi_driver for melodic should be way easier.

**Comment by mbusy** [comment]
This is a bit of a necropost, but naoqi_libqicore (along with naoqi_driver, naoqi_bridge_msgs and the robots meshes) has been released for ros melodic
